name: CPLUG
description: Cal Poly Linux Users Group
highlighter: rouge
permalink: pretty
gems:
  - jekyll-redirect-from
  - jekyll-paginate

markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..2
logo: false
paginate: 5
baseurl: /
